/*
SELECT DISTINCT SPJ1.S#, SPJ1.J#
FROM SPJ AS SPJ1
WHERE (SELECT CITY FROM S WHERE S.S# = SPJ1.S#) 
      = 
	  ALL (SELECT DISTINCT J.CITY FROM J JOIN SPJ ON J.J# = SPJ.J# JOIN S ON SPJ.S# = S.S# WHERE S.S# = SPJ1.S#)
	  */
	  /*
SELECT S.*, P.*, J.*
FROM S
JOIN SPJ ON SPJ.S# = S.S#
JOIN P ON SPJ.P# = P.P#
JOIN J ON SPJ.J# = J.J#;
*/
SELECT S.S#, J.J#, S.CITY AS SCITY, J.CITY AS JCITY
FROM S
JOIN SPJ ON S.S# = SPJ.J#
JOIN J ON SPJ.J# = J.J#
ORDER BY S.S# ASC;
